### ISSUE TITLE
Question: how to set image name, image description etc when capturing a new image

### ISSUE THREAD

**Issue by wingers999** [jeffkl/ManagedWimgApi#32]
Hi

Fantastic API, working perfectly for everything I need - just need to work out how to set information in the image when I capture it e.g. Image Name, Image Description etc

**Comment by jeffkl** [comment]
You'll need to call the `SetImageInformation` method, similar to how [this unit test does it](https://github.com/jeffkl/ManagedWimgApi/blob/master/src/Microsoft.Wim.Tests/ImageInfoTests.cs#L147).  The XML blob might look something like [this](https://github.com/jeffkl/ManagedWimgApi/blob/master/src/Microsoft.Wim.Tests/ImageInfoTests.cs#L49).

The image information is just raw XML and I'm not aware of any API or schema for it.  Even [the official documentation](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/imaging/dd834949(v%3dmsdn.10)) doesn't mention the schema.  I've only seen [this requirement](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/imaging/dd834951(v%3dmsdn.10)#remarks):

> If the input handle is from the WIMCreateFile function, then the XML data must be enclosed by `<WIM></WIM>` tags. If the input handle is from the WIMLoadImage or WIMCaptureImage functions, then the XML data must be enclosed by `<IMAGE></IMAGE>` tags.

For your example, the XML would be:

```xml
<WIM>
  <IMAGE INDEX="1">
    <NAME>My image name</NAME>
    <DESCRIPTION>My image description</DESCRIPTION>
  </IMAGE>
</WIM>
```

**Comment by wingers999** [comment]
Thanks for prompt reply Jeff - think it was the format of the XML I had got wrong as using your example XML seems to have worked for me

For anyone else reading this the code I used (VB rather than C#) which worked is

`   Using wimHandle As WimHandle = WimgApi.CreateFile("D:\test.wim", WimFileAccess.Write, WimCreationDisposition.OpenExisting, WimCreateFileOptions.None, WimCompressionType.None)

            WimgApi.SetTemporaryPath(wimHandle, Environment.GetEnvironmentVariable("TEMP"))

            Dim xmlDocument As New XmlDocument()

            Dim fragment As XmlDocumentFragment = xmlDocument.CreateDocumentFragment()

            fragment.InnerXml = "<WIM>
                                   <IMAGE INDEX=""1"">
                                   <NAME>My image name</NAME>
                                   <DESCRIPTION>My image description</DESCRIPTION>
                                   </IMAGE>
                               </WIM>"

            xmlDocument.AppendChild(fragment)

            WimgApi.SetImageInformation(wimHandle, xmlDocument)

        End Using`

**Comment by jeffkl** [comment]
Awesome, I'm closing this issue then.  Happy coding!
