### ISSUE TITLE
why GetImageInformation returns IXPathNavigable instead of a standard xml

### ISSUE THREAD

**Issue by 424778940z** [jeffkl/ManagedWimgApi#35]
I want set the name for the volume after capture, but IXPathNavigable is read-only, I have to some how convert to xml then edit then convert back to IXPathNavigable then set it

>IXPathNavigable vol_info_xpath = WimgApi.GetImageInformation(des_vol_h);
XPathNavigator vol_info_xpath_nav = vol_info_xpath.CreateNavigator();
XmlDocument vol_info_xml = new XmlDocument();
vol_info_xml.LoadXml(vol_info_xpath_nav.OuterXml);
vol_info_xml.DocumentElement.AppendChild(vol_info_xml.CreateElement("NAME"));
vol_info_xml.DocumentElement.LastChild.AppendChild(vol_info_xml.CreateTextNode(vol_name));
WimgApi.SetImageInformation(des_vol_h, vol_info_xml);

all this dirty block of code just for set a name for a volume...

what is the point of doing so?

**Comment by jeffkl** [comment]
`GetImageInformation` returns just a string so I decided to have it return an interface that `XPathDocument` implements so it would be a fast read-only version of the document for querying.

We could add another method like `GetImageInformationEx` which returns an `XDocument` if you want.

**Comment by 424778940z** [comment]
> `GetImageInformation` returns just a string so I decided to have it return an interface that `XPathDocument` implements so it would be a fast read-only version of the document for querying.
> 
> We could add another method like `GetImageInformationEx` which returns an `XDocument` if you want.

That will be great, or I may suggest let the GetImageInformation return XML by default, GetImageInformationEx return XPathDocument, or just drop the XPathDocument at all.

According to Microsoft XPathDocument is designed for fast read and read only, I think it more designed for web servers not for regular XML uses, I have a WIM with 40 volumes the XML total is only 87KB... There is no point to use a fast fetch model.

**Comment by jeffkl** [comment]
> That will be great, or I may suggest let the GetImageInformation return XML by default, 

Do you want it to return a `string`, `XDocument`, or `XmlDocument`?

**Comment by 424778940z** [comment]
> Do you want it to return a `string`, `XDocument`, or `XmlDocument`?

I think XmlDocument would be the best choice, it's easy to modify and not read only.

**Comment by jeffkl** [comment]
Please check out the proposed PR: #36
