### ISSUE TITLE
Dism /Append-Image

### ISSUE THREAD

**Issue by wingers999** [jeffkl/ManagedWimgApi#45]
Does the API have equivalent of Dism /Append-Image? can't seem to find mention of it anywhere

Thank you

**Comment by jeffkl** [comment]
Yes it should.  I'm not exactly sure how dism.exe does it, but I'd imagine you can get a handle to the main image and call ExportImage on the other.  If you can't figure it out, I can dig into it.

**Comment by wingers999** [comment]
Okay
I have spent a while this afternoon looking through all documentation and code etc, but it is certainly not obvious if it does, for most other functions the commands for wimgapi are similarly named e.g. WimgApi.CaptureImage for Dism /Capture-Image, and WimgApi.ApplyImage for Dism /Apply-Image etc

**Comment by jeffkl** [comment]
Okay it looks like you do the following:

`CreateFile` to create an image
`CaptureImage` to capture original image

`CreateFile` to existing image
`CaptureImage` to capture another image

So append is just capture to an existing image.

**Comment by wingers999** [comment]
Okay that logic makes sense, I will give it a test during weekend and let you know how I get on - thanks

**Comment by wingers999** [comment]
Hi Jeff

I can confirm that logic is correct and it works fine

You just need to make sure you set WimCreationDisposition to OpenAlways rather than CreateAlways

**Comment by jeffkl** [comment]
Great, glad we figured it out!
