### ISSUE TITLE
Anyway to find existing compression type of a WIM?

### ISSUE THREAD

**Issue by wingers999** [jeffkl/ManagedWimgApi#46]
Anyway to find existing compression type of a WIM?

GetImageInfo doesn't seem to return that information? unless I am missing something

Thanks

**Comment by jeffkl** [comment]
Yes, [WimgApi.GetAttributes](https://github.com/jeffkl/ManagedWimgApi/blob/master/src/Microsoft.Wim/WimgApi.GetAttributes.cs#L21) returns a [WimInfo](https://github.com/jeffkl/ManagedWimgApi/blob/master/src/Microsoft.Wim/WimInfo.cs) object which has a has [the compression type](https://github.com/jeffkl/ManagedWimgApi/blob/master/src/Microsoft.Wim/WimInfo.cs#L96).

**Comment by wingers999** [comment]
Thanks Jeff - perfect :)
