### ISSUE TITLE
excluding specified files during capture

### ISSUE THREAD

**Issue by wingers999** [jeffkl/ManagedWimgApi#47]
Hi

With DISM on the command line you can use the /ConfigFile switch to provide a file listing exclusions etc

See here = https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-configuration-list-and-wimscriptini-files-winnext

Can this be done with ManagedWimgApi?

Thanks

**Comment by jeffkl** [comment]
Not at the moment no.  The WIMGAPI has a message callback and one of the messages is WimMessageProcess.  When this is called, WIMGAPI is asking the application if a particular file should be processed.  I'm assuming that dism.exe just loads the config file and uses it to determine which files should be excluded via the WimMessageProcess callback.

Message callback sample is here: https://github.com/jeffkl/ManagedWimgApi/wiki/Message-Callbacks

**Comment by wingers999** [comment]
Thanks, as always your replies point me in the right direction and I now have it working :)
